trainer:
  params:
    max_epochs: 1000
    progress_bar_refresh_rate: 20
  wandb_project: "10701"

model:
  module_name: Dehazeformer
  params:
    in_chans: 12
    out_chans: 13
    embed_dims: [24, 48, 96, 48, 24],
    mlp_ratios: [2., 4., 4., 2., 2.],
    depths: [4, 4, 4, 2, 2],
    num_heads: [2, 4, 6, 1, 1],
    attn_ratio: [0, 1 / 2, 1, 0, 0],
    conv_type: ['DWConv', 'DWConv', 'DWConv', 'DWConv', 'DWConv']

metrics:
  PSNR: torchmetrics.PeakSignalNoiseRatio
  SSIM: torchmetrics.StructuralSimilarityIndexMeasure

criterion:
  L1:
    module_name: nn.L1Loss()
    weight: 0.5
  L2:
    module_name: nn.MSELoss()
    weight: 0.5

datasets:
  train_dataset_params:
    root_dir: "./data/.."
    mode: "train",
    size: 256
    edge_decay: 0
    only_h_flip: False
    quadruple_color_space: True

  validation_dataset_params:
    root_dir: "./data/.."
    mode: "valid",
    size: 256
    edge_decay: 0
    only_h_flip: False
    quadruple_color_space: True

optimization:
  optimizer_module_name: torch.optim.Adam
  optimizer_params:
    lr: 2e-4
  scheduler_module_name: torch.optim.lr_scheduler.CosineAnnealingLR
  schduler_params:
    T_max: 1000
    eta_min: 2e-5
