trainer:
  max_epochs: 1000
  # fast_dev_run: 5
  default_root_dir: "workdir"
  batch_size: 16
  accelerator: "gpu"
  precision: 16

wandb:
  project: "Image Dehazing"
  run_name: "esdnet"
  entity: "10701"

model:
  module_name: ESDNet
  params:
    in_chans: 3
    en_feature_num: 48
    en_inter_num: 32
    de_feature_num: 64
    de_inter_num: 32
    sam_number: 1

metrics:
  valid_psnr:
    module: torchmetrics.PeakSignalNoiseRatio
    params:
      data_range: 1.
      dim: [ 1, 2, 3 ]
      reduction: none
  valid_ssim:
    module: torchmetrics.StructuralSimilarityIndexMeasure
    params:
      data_range: 1.
      reduction: none

criterion:
  L1:
    module_name: nn.L1Loss()
    weight: 1.
#  L2:
#    module_name: nn.MSELoss()
#    weight: 0.5

datasets:
  train_dataset_params:
    root_dir: "./data/RESIDE-6K/train/"
    mode: "train"
    size: 256
    edge_decay: 0
    only_h_flip: False
    quadruple_color_space: False

  validation_dataset_params:
    root_dir: "./data/RESIDE-6K/test/"
    mode: "valid"
    size: 256
    edge_decay: 0
    only_h_flip: False
    quadruple_color_space: False

optimization:
  optimizer_module_name: torch.optim.Adam
  optimizer_params:
    lr: 0.0002
  scheduler_module_name: torch.optim.lr_scheduler.CosineAnnealingLR
  scheduler_params:
    T_max: 1000
    eta_min: 0.000002
